# Generated by Django 5.1.4 on 2025-01-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lastname',
        ),
    ]
